import { LoanApplication, OfficerWorkload, OverviewStats, SlaBottleneck, EarlyWarningItem, User } from './types';

export const DEMO_USERS: Record<string, User> = {
  cbtd_nam: {
    id: 'user-cbtd-1',
    username: 'cbtd_nam',
    fullName: 'Nguyễn Văn Nam',
    email: 'nam.nv@bank.com.vn',
    phone: '0903112233',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['CBTD'],
  },
  risk_quang: {
    id: 'user-risk-1',
    username: 'risk_quang',
    fullName: 'Trần Thị Quang',
    email: 'quang.tt@bank.com.vn',
    phone: '0918445566',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['THAM_QUYEN'],
  },
  manager_dung: {
    id: 'user-mgr-1',
    username: 'manager_dung',
    fullName: 'Lê Hoàng Dũng',
    email: 'dung.lh@bank.com.vn',
    phone: '0988776655',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['QUAN_LY'],
  },
  admin: {
    id: 'user-admin-1',
    username: 'admin',
    fullName: 'Quản trị viên Hệ thống',
    email: 'admin@bank.com.vn',
    phone: '0909999999',
    branchName: 'Hội sở chính',
    roles: ['ADMIN'],
  },
};

export const INITIAL_MOCK_LOANS: LoanApplication[] = [
  {
    id: 'loan-mock-1',
    applicationCode: 'SME-20260928-0001',
    companyId: 'comp-1',
    company: {
      id: 'comp-1',
      taxCode: '0312345678',
      companyName: 'Công ty Cổ phần Thép Việt Á',
      industry: 'Sản xuất & Chế biến kim loại',
      establishedYear: 2017,
      annualRevenue: 52000000000,
      charterCapital: 15000000000,
      representativeName: 'Vũ Mạnh Hùng',
      phone: '0908123456',
      address: 'Khu công nghiệp Tân Bình, TP. Hồ Chí Minh',
    },
    loanPurpose: 'Bổ sung vốn lưu động thu mua phôi thép phục vụ đơn hàng xuất khẩu quý 4',
    loanType: 'VAY_VON_LUU_DONG',
    proposedAmount: 6000000000,
    officialAmount: 5500000000,
    loanTermMonths: 12,
    currentStage: 'TIEP_NHAN',
    currentStatus: 'CHECKED',
    assignedTo: 'user-cbtd-1',
    assignedUser: {
      id: 'user-cbtd-1',
      fullName: 'Nguyễn Văn Nam',
      username: 'cbtd_nam',
      email: 'nam.nv@bank.com.vn',
    },
    isDocumentComplete: true,
    supplementCount: 0,
    createdAt: '2026-09-28T08:15:00Z',
    updatedAt: '2026-09-28T09:30:00Z',
    stageHistories: [
      {
        id: 'hist-1',
        stageId: 'stage-1',
        stage: { stageCode: 'TIEP_NHAN', stageName: 'Tiếp nhận hồ sơ', standardSlaHours: 4 },
        enteredAt: '2026-09-28T08:15:00Z',
        exitedAt: undefined,
        actualDurationHours: 1.5,
        pausedDurationHours: 0,
        netWorkDurationHours: 1.5,
        slaStandardHours: 4,
        isDelayed: false,
        notes: 'Hồ sơ đã được kiểm tra đầy đủ danh mục chứng từ pháp lý và báo cáo tài chính',
        handler: { fullName: 'Nguyễn Văn Nam', username: 'cbtd_nam' },
      },
    ],
    documents: [
      { id: 'doc-1', documentType: 'PHAP_LY', fileName: 'Giay_Phep_Kinh_Doanh_2025.pdf', filePath: '/docs/gpkd.pdf', fileSize: 1845000, uploadedAt: '2026-09-28T08:20:00Z', uploader: { fullName: 'Nguyễn Văn Nam' } },
      { id: 'doc-2', documentType: 'TAI_CHINH', fileName: 'Bao_Cao_Tai_Chinh_Kiem_Toan_2025.pdf', filePath: '/docs/bctc.pdf', fileSize: 4200000, uploadedAt: '2026-09-28T08:25:00Z', uploader: { fullName: 'Nguyễn Văn Nam' } },
    ],
    delayPredictions: [
      {
        id: 'pred-1',
        applicationId: 'loan-mock-1',
        riskLevel: 'THAP',
        delayProbability: 0.08,
        topReasonsJson: JSON.stringify(['Hồ sơ đầy đủ chứng từ ngay từ đầu', 'Doanh nghiệp 8 năm hoạt động có doanh thu ổn định']),
        modelVersion: 'RandomForest-v1.0',
        predictionTimestamp: '2026-09-28T08:30:00Z',
      },
    ],
  },
  {
    id: 'loan-mock-2',
    applicationCode: 'SME-20260928-0002',
    companyId: 'comp-2',
    company: {
      id: 'comp-2',
      taxCode: '0319876543',
      companyName: 'Công ty TNHH Dệt May Hưng Phát',
      industry: 'Sản xuất & Dệt may',
      establishedYear: 2019,
      annualRevenue: 28000000000,
      charterCapital: 8000000000,
      representativeName: 'Phạm Thị Lan',
      phone: '0912334455',
      address: 'Cụm công nghiệp Nhị Xuân, Hóc Môn, TP.HCM',
    },
    loanPurpose: 'Đầu tư dây chuyền máy may tự động hóa mở rộng nhà xưởng số 2',
    loanType: 'VAY_DAU_TU_TSCD',
    proposedAmount: 8500000000,
    officialAmount: 8000000000,
    loanTermMonths: 36,
    currentStage: 'THAM_DINH',
    currentStatus: 'PENDING_APPRAISAL',
    assignedTo: 'user-cbtd-1',
    assignedUser: {
      id: 'user-cbtd-1',
      fullName: 'Nguyễn Văn Nam',
      username: 'cbtd_nam',
      email: 'nam.nv@bank.com.vn',
    },
    isDocumentComplete: true,
    supplementCount: 1,
    createdAt: '2026-09-27T10:00:00Z',
    updatedAt: '2026-09-28T10:15:00Z',
    stageHistories: [
      {
        id: 'hist-2-1',
        stageId: 'stage-1',
        stage: { stageCode: 'TIEP_NHAN', stageName: 'Tiếp nhận hồ sơ', standardSlaHours: 4 },
        enteredAt: '2026-09-27T10:00:00Z',
        exitedAt: '2026-09-27T13:30:00Z',
        actualDurationHours: 3.5,
        pausedDurationHours: 0,
        netWorkDurationHours: 3.5,
        slaStandardHours: 4,
        isDelayed: false,
        notes: 'Tiếp nhận và kiểm tra hồ sơ đúng định mức',
        handler: { fullName: 'Nguyễn Văn Nam', username: 'cbtd_nam' },
      },
      {
        id: 'hist-2-2',
        stageId: 'stage-2',
        stage: { stageCode: 'THAM_DINH', stageName: 'Thẩm định tín dụng', standardSlaHours: 12 },
        enteredAt: '2026-09-27T13:30:00Z',
        exitedAt: undefined,
        actualDurationHours: 8.0,
        pausedDurationHours: 1.5,
        netWorkDurationHours: 6.5,
        slaStandardHours: 12,
        isDelayed: false,
        notes: 'Đang tiến hành thẩm định thực địa tại nhà xưởng',
        handler: { fullName: 'Trần Thị Quang', username: 'risk_quang' },
      },
    ],
    documents: [
      { id: 'doc-2-1', documentType: 'PHAP_LY', fileName: 'GPKD_Hung_Phat.pdf', filePath: '/docs/gpkd2.pdf', fileSize: 2100000, uploadedAt: '2026-09-27T10:10:00Z' },
      { id: 'doc-2-2', documentType: 'PHUONG_AN', fileName: 'Phuong_An_Vay_Von_May_Moc.pdf', filePath: '/docs/pa2.pdf', fileSize: 3500000, uploadedAt: '2026-09-27T10:15:00Z' },
      { id: 'doc-2-3', documentType: 'TSBD', fileName: 'Giay_Chung_Nhan_QSD_Dat_Xuong.pdf', filePath: '/docs/tsbd2.pdf', fileSize: 5800000, uploadedAt: '2026-09-27T10:20:00Z' },
    ],
    supplementRequests: [
      {
        id: 'supp-2-1',
        applicationId: 'loan-mock-2',
        requestContent: 'Bổ sung hợp đồng mua bán máy móc thiết bị nhập khẩu từ Nhật Bản',
        requestedAt: '2026-09-27T14:00:00Z',
        resolvedAt: '2026-09-27T15:30:00Z',
        status: 'RESOLVED',
        notes: 'Doanh nghiệp đã nộp bổ sung bản scan hợp đồng và invoice',
        requester: { fullName: 'Nguyễn Văn Nam', username: 'cbtd_nam' },
      },
    ],
    delayPredictions: [
      {
        id: 'pred-2',
        applicationId: 'loan-mock-2',
        riskLevel: 'TRUNG_BINH',
        delayProbability: 0.42,
        topReasonsJson: JSON.stringify(['Đã có 1 lần yêu cầu bổ sung chứng từ', 'Thời gian thẩm định tài sản máy móc phức tạp']),
        modelVersion: 'RandomForest-v1.0',
        predictionTimestamp: '2026-09-28T09:00:00Z',
      },
    ],
  },
  {
    id: 'loan-mock-3',
    applicationCode: 'SME-20260928-0003',
    companyId: 'comp-3',
    company: {
      id: 'comp-3',
      taxCode: '0315556677',
      companyName: 'Công ty Cổ phần Xây dựng & Hạ tầng Đô thị Đại Nam',
      industry: 'Xây dựng & Thi công công trình',
      establishedYear: 2016,
      annualRevenue: 98000000000,
      charterCapital: 30000000000,
      representativeName: 'Hoàng Quốc Việt',
      phone: '0909887766',
      address: 'Số 182 Lê Duẩn, Quận 1, TP. Hồ Chí Minh',
    },
    loanPurpose: 'Tài trợ thi công gói thầu hạ tầng kỹ thuật khu công nghiệp xanh (Vượt thẩm quyền chi nhánh)',
    loanType: 'VAY_DAU_TU_TSCD',
    proposedAmount: 22000000000,
    officialAmount: 20000000000,
    loanTermMonths: 48,
    currentStage: 'CAP_TREN',
    currentStatus: 'WAITING_HEAD_OFFICE',
    assignedTo: 'user-cbtd-1',
    assignedUser: {
      id: 'user-cbtd-1',
      fullName: 'Nguyễn Văn Nam',
      username: 'cbtd_nam',
      email: 'nam.nv@bank.com.vn',
    },
    isDocumentComplete: true,
    supplementCount: 2,
    createdAt: '2026-09-25T08:30:00Z',
    updatedAt: '2026-09-28T08:00:00Z',
    stageHistories: [
      {
        id: 'hist-3-1',
        stageId: 'stage-1',
        stage: { stageCode: 'TIEP_NHAN', stageName: 'Tiếp nhận hồ sơ', standardSlaHours: 4 },
        enteredAt: '2026-09-25T08:30:00Z',
        exitedAt: '2026-09-25T11:45:00Z',
        actualDurationHours: 3.2,
        pausedDurationHours: 0,
        netWorkDurationHours: 3.2,
        slaStandardHours: 4,
        isDelayed: false,
        notes: 'Tiếp nhận thành công',
      },
      {
        id: 'hist-3-2',
        stageId: 'stage-2',
        stage: { stageCode: 'THAM_DINH', stageName: 'Thẩm định tín dụng', standardSlaHours: 12 },
        enteredAt: '2026-09-25T11:45:00Z',
        exitedAt: '2026-09-26T16:00:00Z',
        actualDurationHours: 16.0,
        pausedDurationHours: 3.0,
        netWorkDurationHours: 13.0,
        slaStandardHours: 12,
        isDelayed: true,
        notes: 'Hồ sơ quy mô lớn (> 20 tỷ), thẩm định hợp đồng thầu phức tạp',
      },
      {
        id: 'hist-3-3',
        stageId: 'stage-3',
        stage: { stageCode: 'CAP_TREN', stageName: 'Hội đồng / Cấp trên', standardSlaHours: 24 },
        enteredAt: '2026-09-26T16:00:00Z',
        exitedAt: undefined,
        actualDurationHours: 18.5,
        pausedDurationHours: 0,
        netWorkDurationHours: 18.5,
        slaStandardHours: 24,
        isDelayed: false,
        notes: 'Đang trình Hội đồng tín dụng biểu quyết',
      },
    ],
    documents: [
      { id: 'doc-3-1', documentType: 'PHAP_LY', fileName: 'Ho_So_Phap_Ly_Dai_Nam.pdf', filePath: '/docs/pl3.pdf', fileSize: 8500000, uploadedAt: '2026-09-25T08:45:00Z' },
      { id: 'doc-3-2', documentType: 'PHUONG_AN', fileName: 'Hop_Dong_Goi_Thau_Thi_Cong.pdf', filePath: '/docs/hd3.pdf', fileSize: 12400000, uploadedAt: '2026-09-25T09:00:00Z' },
    ],
    supplementRequests: [
      { id: 'supp-3-1', applicationId: 'loan-mock-3', requestContent: 'Bổ sung bảo lãnh dự thầu và phụ lục tiến độ', requestedAt: '2026-09-25T14:00:00Z', resolvedAt: '2026-09-25T16:30:00Z', status: 'RESOLVED' },
      { id: 'supp-3-2', applicationId: 'loan-mock-3', requestContent: 'Bổ sung biên bản định giá tài sản quyền đòi nợ', requestedAt: '2026-09-26T09:00:00Z', resolvedAt: '2026-09-26T10:30:00Z', status: 'RESOLVED' },
    ],
    delayPredictions: [
      {
        id: 'pred-3',
        applicationId: 'loan-mock-3',
        riskLevel: 'CAO',
        delayProbability: 0.89,
        topReasonsJson: JSON.stringify(['Hồ sơ đã yêu cầu bổ sung 2 lần (+35% nguy cơ trễ)', 'Khoản vay 20 tỷ vượt hạn mức chi nhánh phải qua Hội đồng', 'Cán bộ đang phụ trách khối lượng hồ sơ lớn']),
        modelVersion: 'RandomForest-v1.0',
        predictionTimestamp: '2026-09-28T08:00:00Z',
      },
    ],
  },
  {
    id: 'loan-mock-4',
    applicationCode: 'SME-20260928-0004',
    companyId: 'comp-4',
    company: {
      id: 'comp-4',
      taxCode: '0314443322',
      companyName: 'Công ty TNHH Thương mại Dịch vụ Nam Long',
      industry: 'Thương mại - Dịch vụ & Phân phối',
      establishedYear: 2021,
      annualRevenue: 16000000000,
      charterCapital: 5000000000,
      representativeName: 'Đặng Thanh Tùng',
      phone: '0977112233',
      address: '45 Đường số 7, Phường An Phú, TP. Thủ Đức',
    },
    loanPurpose: 'Vay thấu chi tài khoản thanh toán tiền hàng đại lý',
    loanType: 'THAU_CHI',
    proposedAmount: 2000000000,
    officialAmount: 2000000000,
    approvedAmount: 2000000000,
    interestRate: 8.2,
    loanTermMonths: 12,
    currentStage: 'HOAN_TAT',
    currentStatus: 'APPROVED',
    assignedTo: 'user-cbtd-1',
    assignedUser: {
      id: 'user-cbtd-1',
      fullName: 'Nguyễn Văn Nam',
      username: 'cbtd_nam',
    },
    isDocumentComplete: true,
    supplementCount: 0,
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-27T15:00:00Z',
    completedAt: '2026-09-27T15:00:00Z',
    stageHistories: [
      { id: 'hist-4-1', stageId: 's1', enteredAt: '2026-09-26T09:00:00Z', exitedAt: '2026-09-26T11:30:00Z', actualDurationHours: 2.5, pausedDurationHours: 0, netWorkDurationHours: 2.5, slaStandardHours: 4, isDelayed: false, stage: { stageCode: 'TIEP_NHAN', stageName: 'Tiếp nhận', standardSlaHours: 4 } },
      { id: 'hist-4-2', stageId: 's2', enteredAt: '2026-09-26T11:30:00Z', exitedAt: '2026-09-27T10:00:00Z', actualDurationHours: 8.5, pausedDurationHours: 0, netWorkDurationHours: 8.5, slaStandardHours: 12, isDelayed: false, stage: { stageCode: 'THAM_DINH', stageName: 'Thẩm định', standardSlaHours: 12 } },
      { id: 'hist-4-3', stageId: 's4', enteredAt: '2026-09-27T10:00:00Z', exitedAt: '2026-09-27T15:00:00Z', actualDurationHours: 2.0, pausedDurationHours: 0, netWorkDurationHours: 2.0, slaStandardHours: 4, isDelayed: false, stage: { stageCode: 'HOAN_TAT', stageName: 'Hoàn tất & Phê duyệt', standardSlaHours: 4 } },
    ],
    delayPredictions: [
      { id: 'pred-4', applicationId: 'loan-mock-4', riskLevel: 'THAP', delayProbability: 0.05, topReasonsJson: JSON.stringify(['Hồ sơ quy mô nhỏ duyệt nhanh', 'Lịch sử dòng tiền đại lý minh bạch']), modelVersion: 'RandomForest-v1.0', predictionTimestamp: '2026-09-26T11:30:00Z' },
    ],
  },
  {
    id: 'loan-mock-5',
    applicationCode: 'SME-20260928-0005',
    companyId: 'comp-5',
    company: {
      id: 'comp-5',
      taxCode: '0318889900',
      companyName: 'Công ty Cổ phần Đầu tư Logistics Miền Đông',
      industry: 'Vận tải & Kho bãi Logistics',
      establishedYear: 2020,
      annualRevenue: 22000000000,
      charterCapital: 6000000000,
      representativeName: 'Trịnh Văn Cường',
      phone: '0933221100',
      address: 'Kho bãi KCN Cát Lái, TP. Thủ Đức',
    },
    loanPurpose: 'Đầu tư mở rộng đội xe kéo container 5 chiếc',
    loanType: 'VAY_DAU_TU_TSCD',
    proposedAmount: 7000000000,
    officialAmount: 7000000000,
    loanTermMonths: 36,
    currentStage: 'HOAN_TAT',
    currentStatus: 'REJECTED',
    rejectionReasonCode: 'TC02',
    rejectionNote: 'Dòng tiền kinh doanh 6 tháng gần nhất âm, nợ vay ngắn hạn tại các TCTD khác vượt 3 lần vốn chủ sở hữu',
    assignedTo: 'user-cbtd-1',
    assignedUser: { id: 'user-cbtd-1', fullName: 'Nguyễn Văn Nam', username: 'cbtd_nam' },
    isDocumentComplete: true,
    supplementCount: 1,
    createdAt: '2026-09-24T08:00:00Z',
    completedAt: '2026-09-25T16:00:00Z',
    updatedAt: '2026-09-25T16:00:00Z',
    delayPredictions: [
      { id: 'pred-5', applicationId: 'loan-mock-5', riskLevel: 'CAO', delayProbability: 0.76, topReasonsJson: JSON.stringify(['Khả năng trả nợ suy giảm', 'Tỷ lệ nợ/vốn chủ sở hữu quá cao']), modelVersion: 'RandomForest-v1.0', predictionTimestamp: '2026-09-24T14:00:00Z' },
    ],
  },
  {
    id: 'loan-mock-6',
    applicationCode: 'SME-20260928-0006',
    companyId: 'comp-6',
    company: {
      id: 'comp-6',
      taxCode: '0317778899',
      companyName: 'Công ty TNHH Nông sản Hữu cơ Xanh',
      industry: 'Nông nghiệp & Chế biến thực phẩm',
      establishedYear: 2022,
      annualRevenue: 14000000000,
      charterCapital: 4500000000,
      representativeName: 'Lê Thu Trang',
      phone: '0944556677',
      address: 'Ấp 4, Xã Tân Thạnh Đông, Củ Chi, TP.HCM',
    },
    loanPurpose: 'Vay bổ sung vốn thu mua nông sản theo vụ mùa',
    loanType: 'VAY_VON_LUU_DONG',
    proposedAmount: 3000000000,
    officialAmount: 3000000000,
    loanTermMonths: 6,
    currentStage: 'THAM_DINH',
    currentStatus: 'SUPPLEMENT_REQUIRED',
    assignedTo: 'user-cbtd-1',
    assignedUser: { id: 'user-cbtd-1', fullName: 'Nguyễn Văn Nam', username: 'cbtd_nam' },
    isDocumentComplete: false,
    supplementCount: 2,
    createdAt: '2026-09-27T14:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
    supplementRequests: [
      {
        id: 'supp-6-1',
        applicationId: 'loan-mock-6',
        requestContent: 'Bổ sung hợp đồng nguyên tắc bao tiêu đầu ra với chuỗi siêu thị',
        requestedAt: '2026-09-28T09:00:00Z',
        status: 'PENDING',
        notes: 'Đang tạm dừng SLA chờ khách hàng cung cấp',
        requester: { fullName: 'Trần Thị Quang', username: 'risk_quang' },
      },
    ],
    delayPredictions: [
      {
        id: 'pred-6',
        applicationId: 'loan-mock-6',
        riskLevel: 'CAO',
        delayProbability: 0.84,
        topReasonsJson: JSON.stringify(['Hồ sơ đang tạm dừng chờ bổ sung chứng từ lần 2', 'Thời gian hoàn tất thủ tục kéo dài']),
        modelVersion: 'RandomForest-v1.0',
        predictionTimestamp: '2026-09-28T09:05:00Z',
      },
    ],
  },
];

export const DEMO_WORKLOADS: OfficerWorkload[] = [
  {
    id: 'user-cbtd-2',
    fullName: 'Hoàng Văn Hùng',
    username: 'cbtd_hung',
    phone: '0908889911',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['CBTD'],
    activeLoanCount: 2,
    highRiskLoanCount: 0,
    workloadStatus: 'KHẢ DỤNG',
  },
  {
    id: 'user-risk-1',
    fullName: 'Trần Thị Quang',
    username: 'risk_quang',
    phone: '0918445566',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['THAM_QUYEN'],
    activeLoanCount: 5,
    highRiskLoanCount: 1,
    workloadStatus: 'KHẢ DỤNG',
  },
  {
    id: 'user-cbtd-1',
    fullName: 'Nguyễn Văn Nam',
    username: 'cbtd_nam',
    phone: '0903112233',
    branchName: 'Chi nhánh TP.HCM',
    roles: ['CBTD'],
    activeLoanCount: 11,
    highRiskLoanCount: 3,
    workloadStatus: 'QUÁ TẢI',
  },
];

export const DEMO_STATS: OverviewStats = {
  totalApplications: 28,
  activeApplications: 8,
  approvedApplications: 16,
  rejectedApplications: 3,
  timeoutApplications: 1,
  totalCompletedStages: 64,
  delayedStages: 6,
  slaOnTimeRate: 90.6,
  highRiskLoans: 3,
};

export const DEMO_BOTTLENECKS: SlaBottleneck[] = [
  {
    stageCode: 'TIEP_NHAN',
    stageName: 'Tiếp nhận & Kiểm tra hồ sơ',
    standardSlaHours: 4,
    totalHandled: 28,
    delayedCount: 1,
    delayRate: 3.6,
    avgNetWorkHours: 2.8,
    isBottleneck: false,
  },
  {
    stageCode: 'THAM_DINH',
    stageName: 'Thẩm định tín dụng & Định giá',
    standardSlaHours: 12,
    totalHandled: 24,
    delayedCount: 4,
    delayRate: 16.7,
    avgNetWorkHours: 13.2,
    isBottleneck: true, // Điểm nghẽn
  },
  {
    stageCode: 'CAP_TREN',
    stageName: 'Phê duyệt Cấp trên / Hội đồng',
    standardSlaHours: 24,
    totalHandled: 7,
    delayedCount: 1,
    delayRate: 14.3,
    avgNetWorkHours: 20.4,
    isBottleneck: false,
  },
  {
    stageCode: 'HOAN_TAT',
    stageName: 'Hoàn tất thủ tục & Giải ngân',
    standardSlaHours: 4,
    totalHandled: 19,
    delayedCount: 0,
    delayRate: 0.0,
    avgNetWorkHours: 2.1,
    isBottleneck: false,
  },
];
